import { Ionicons } from '@expo/vector-icons';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import {
  Alert,
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  Switch,
  Text,
  View,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import { useColorScheme } from '@/components/useColorScheme';
import Colors from '@/constants/Colors';
import { font } from '@/constants/typography';
import { useMedConnect } from '@/context/MedConnectContext';

type PdfMetricKey = 'bp' | 'hr' | 'bmi' | 'spo2' | 'rhythm' | 'glucose' | 'chol';

type PdfMetricInclude = Record<PdfMetricKey, boolean>;

const PDF_METRICS: { key: PdfMetricKey; label: string; icon: keyof typeof Ionicons.glyphMap }[] = [
  { key: 'bp', label: 'Blood pressure', icon: 'pulse-outline' },
  { key: 'hr', label: 'Heart rate', icon: 'heart-outline' },
  { key: 'bmi', label: 'BMI', icon: 'body-outline' },
  { key: 'spo2', label: 'Blood oxygen (SpO2)', icon: 'water-outline' },
  { key: 'rhythm', label: 'Irregular heartbeat', icon: 'heart-circle-outline' },
  { key: 'glucose', label: 'Est. glucose', icon: 'flask-outline' },
  { key: 'chol', label: 'Est. cholesterol', icon: 'analytics-outline' },
];

export default function ProfileScreen() {
  const router = useRouter();
  const scheme = useColorScheme() ?? 'light';
  const c = Colors[scheme];
  const insets = useSafeAreaInsets();
  const {
    profile,
    guestMode,
    screenings,
    insights,
    notificationsEnabled,
    setNotificationsEnabled,
    scheduleRescreenReminder,
    deleteAllUserData,
    signOut,
  } = useMedConnect();
  const [includeMetrics, setIncludeMetrics] = useState<PdfMetricInclude>({
    bp: true,
    hr: true,
    bmi: true,
    spo2: true,
    rhythm: true,
    glucose: true,
    chol: true,
  });
  const [busy, setBusy] = useState(false);

  const buildPdfHtml = () => {
    const latest = [...screenings].sort((a, b) => +new Date(b.syncedAt) - +new Date(a.syncedAt))[0];
    const rows = screenings
      .slice()
      .sort((a, b) => +new Date(b.syncedAt) - +new Date(a.syncedAt))
      .slice(0, 6)
      .map(
        (s) => `
      <tr>
        <td>${new Date(s.syncedAt).toLocaleDateString()}</td>
        <td>${includeMetrics.bp ? `${s.bloodPressure.systolic}/${s.bloodPressure.diastolic}` : '—'}</td>
        <td>${includeMetrics.hr ? s.heartRateBpm : '—'}</td>
        <td>${includeMetrics.bmi ? s.bmi.toFixed(1) : '—'}</td>
        <td>${includeMetrics.spo2 ? s.spo2 : '—'}</td>
        <td>${includeMetrics.rhythm ? (s.irregularHeartbeat ? 'Flag' : 'None') : '—'}</td>
        <td>${includeMetrics.glucose ? s.estimatedGlucoseMgDl : '—'}</td>
        <td>${includeMetrics.chol ? s.estimatedCholesterolMgDl : '—'}</td>
      </tr>`
      )
      .join('');

    const insightLines = insights
      .slice(0, 8)
      .map(
        (i) =>
          `<li><strong>${i.title}</strong> — ${i.body} <em>Next:</em> ${i.whatNext}</li>`
      )
      .join('');

    const patient = guestMode
      ? 'Guest user (unverified)'
      : `${profile?.name ?? ''} · DOB ${profile?.dateOfBirth ?? 'n/a'}`;

    return `<!DOCTYPE html>
<html><head><meta charset="utf-8"/><style>
body{font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;padding:24px;color:#111;}
h1{font-size:20px;margin:0 0 8px;}
p{margin:4px 0 16px;color:#444;font-size:13px;}
table{width:100%;border-collapse:collapse;font-size:12px;}
th,td{border:1px solid #ccc;padding:6px;text-align:left;}
th{background:#f3f4f6;}
ul{font-size:12px;line-height:1.5;}
</style></head><body>
<h1>Preventive screening summary</h1>
<p>${patient}</p>
<p>Wellness kiosk snapshots only — not a diagnosis. Estimates are labeled where applicable.</p>
${latest ? `<p><strong>Most recent:</strong> ${new Date(latest.syncedAt).toLocaleString()} at ${latest.location.name}</p>` : ''}
<table>
<thead><tr><th>Date</th><th>BP</th><th>HR</th><th>BMI</th><th>SpO2</th><th>Rhythm</th><th>Est. glucose</th><th>Est. chol</th></tr></thead>
<tbody>${rows}</tbody>
</table>
<h2 style="margin-top:20px;font-size:16px;">Wellness notes (non-diagnostic)</h2>
<ul>${insightLines || '<li>No insights generated.</li>'}</ul>
<p style="margin-top:24px;font-size:11px;color:#666;">Generated by user request from MedConnect demo app. For clinician review only.</p>
</body></html>`;
  };

  const exportPdf = async () => {
    setBusy(true);
    try {
      const html = buildPdfHtml();
      const { uri } = await Print.printToFileAsync({ html });
      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: 'Share summary' });
      } else {
        Alert.alert('PDF ready', uri);
      }
    } catch (e) {
      Alert.alert('Export failed', String(e));
    } finally {
      setBusy(false);
    }
  };

  const onToggleNotify = async (v: boolean) => {
    await setNotificationsEnabled(v);
    if (v) await scheduleRescreenReminder();
  };

  const cardShadow = Platform.select({
    ios: {
      shadowColor: '#0c1929',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.06,
      shadowRadius: 14,
    },
    android: { elevation: 3 },
    default: {},
  });

  const initials =
    !guestMode && profile?.name
      ? profile.name
          .split(' ')
          .map((p) => p[0])
          .join('')
          .slice(0, 2)
          .toUpperCase()
      : null;

  return (
    <ScrollView
      style={[styles.root, { backgroundColor: c.background }]}
      contentContainerStyle={[styles.pad, { paddingBottom: 120 + insets.bottom }]}
      showsVerticalScrollIndicator={false}>
      <View style={[styles.identityCard, { backgroundColor: c.card, borderColor: c.border }, cardShadow]}>
        <View style={[styles.avatar, { backgroundColor: `${c.tint}18` }]}>
          {initials ? (
            <Text style={[styles.avatarText, { color: c.tint, fontFamily: font.bold }]}>{initials}</Text>
          ) : (
            <Ionicons name="person" size={28} color={c.tint} />
          )}
        </View>
        <View style={styles.identityBody}>
          <View style={styles.identityTop}>
            <Text style={[styles.identityName, { color: c.text, fontFamily: font.bold }]} numberOfLines={1}>
              {guestMode ? 'Guest' : profile?.name ?? 'Profile'}
            </Text>
            {guestMode ? (
              <View style={[styles.guestPill, { backgroundColor: c.cardMuted }]}>
                <Text style={[styles.guestPillText, { color: c.textSecondary, fontFamily: font.semiBold }]}>
                  Guest
                </Text>
              </View>
            ) : null}
          </View>
          {!guestMode && profile ? (
            <>
              <View style={styles.metaRow}>
                <Ionicons name="mail-outline" size={16} color={c.textMuted} />
                <Text style={[styles.metaText, { color: c.textSecondary, fontFamily: font.regular }]} numberOfLines={1}>
                  {profile.email}
                </Text>
              </View>
              <View style={styles.metaRow}>
                <Ionicons name="calendar-outline" size={16} color={c.textMuted} />
                <Text style={[styles.metaText, { color: c.textSecondary, fontFamily: font.regular }]}>
                  Born {profile.dateOfBirth}
                </Text>
              </View>
            </>
          ) : (
            <Text style={[styles.guestNote, { color: c.textSecondary, fontFamily: font.regular }]}>
              Data stays on this device in the demo. Sign in with a full account in production.
            </Text>
          )}
        </View>
      </View>

      <Text style={[styles.sectionLabel, { color: c.textMuted, fontFamily: font.semiBold }]}>Notifications</Text>
      <View style={[styles.settingsCard, { backgroundColor: c.card, borderColor: c.border }, cardShadow]}>
        <View style={styles.settingsRow}>
          <View style={[styles.rowIcon, { backgroundColor: `${c.tint}14` }]}>
            <Ionicons name="notifications-outline" size={22} color={c.tint} />
          </View>
          <View style={styles.settingsRowText}>
            <Text style={[styles.rowTitle, { color: c.text, fontFamily: font.semiBold }]}>Re-screening reminders</Text>
            <Text style={[styles.rowSub, { color: c.textSecondary, fontFamily: font.regular }]}>
              Local schedules: higher risk sooner (~30d), lower ~90d.
            </Text>
          </View>
          <Switch
            value={notificationsEnabled}
            onValueChange={(v) => void onToggleNotify(v)}
            trackColor={{ false: c.cardMuted, true: `${c.tint}55` }}
            thumbColor={Platform.OS === 'ios' ? undefined : '#fff'}
            ios_backgroundColor={c.cardMuted}
          />
        </View>
      </View>

      <Text style={[styles.sectionLabel, { color: c.textMuted, fontFamily: font.semiBold }]}>Provider summary</Text>
      <Text style={[styles.sectionHint, { color: c.textSecondary, fontFamily: font.regular }]}>
        Pick what goes in the PDF, then share it with your clinician.
      </Text>

      <View style={[styles.settingsCard, { backgroundColor: c.card, borderColor: c.border }, cardShadow]}>
        {PDF_METRICS.map((row, index) => (
          <View key={row.key}>
            {index > 0 ? <View style={[styles.rowHairline, { backgroundColor: c.border }]} /> : null}
            <View style={styles.metricToggleRow}>
              <View style={[styles.rowIconSm, { backgroundColor: c.cardMuted }]}>
                <Ionicons name={row.icon} size={18} color={c.tint} />
              </View>
              <Text style={[styles.metricLabel, { color: c.text, fontFamily: font.regular }]}>{row.label}</Text>
              <Switch
                value={includeMetrics[row.key]}
                onValueChange={(v) => setIncludeMetrics((s) => ({ ...s, [row.key]: v }))}
                trackColor={{ false: c.cardMuted, true: `${c.tint}55` }}
                thumbColor={Platform.OS === 'ios' ? undefined : '#fff'}
                ios_backgroundColor={c.cardMuted}
              />
            </View>
          </View>
        ))}
      </View>

      <Pressable
        style={({ pressed }) => [
          styles.primaryBtn,
          { backgroundColor: c.ctaFill, opacity: busy ? 0.65 : pressed ? 0.92 : 1 },
          Platform.select({
            ios: {
              shadowColor: '#2563eb',
              shadowOffset: { width: 0, height: 8 },
              shadowOpacity: 0.2,
              shadowRadius: 14,
            },
            android: { elevation: 4 },
            default: {},
          }),
        ]}
        disabled={busy}
        onPress={() => void exportPdf()}>
        <Ionicons name="document-text-outline" size={21} color="#fff" />
        <Text style={[styles.primaryBtnText, { fontFamily: font.bold }]}>
          {busy ? 'Preparing PDF…' : 'Generate & share PDF'}
        </Text>
      </Pressable>

      <Text style={[styles.sectionLabel, { color: c.textMuted, fontFamily: font.semiBold }]}>Account</Text>
      <Pressable
        style={({ pressed }) => [
          styles.dangerBtn,
          { borderColor: 'rgba(220, 38, 38, 0.45)', backgroundColor: pressed ? 'rgba(220, 38, 38, 0.06)' : 'transparent' },
        ]}
        onPress={() => {
          Alert.alert('Delete all data?', 'Removes profile and screenings from this device.', [
            { text: 'Cancel', style: 'cancel' },
            {
              text: 'Delete',
              style: 'destructive',
              onPress: () => {
                void deleteAllUserData();
                router.replace('/onboarding');
              },
            },
          ]);
        }}>
        <Ionicons name="trash-outline" size={20} color="#dc2626" />
        <Text style={[styles.dangerBtnText, { fontFamily: font.semiBold }]}>Delete all my data</Text>
      </Pressable>
      <Pressable
        style={({ pressed }) => [
          styles.secondaryBtn,
          { borderColor: c.border, backgroundColor: pressed ? c.cardMuted : c.card },
          cardShadow,
        ]}
        onPress={() => {
          void signOut();
          router.replace('/onboarding');
        }}>
        <Ionicons name="log-out-outline" size={20} color={c.tint} />
        <Text style={[styles.secondaryBtnText, { color: c.tint, fontFamily: font.bold }]}>Sign out</Text>
      </Pressable>

      <Text style={[styles.footer, { color: c.textMuted, fontFamily: font.regular }]}>
        In production, Face ID or fingerprint can protect this screen.
      </Text>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1 },
  pad: { paddingHorizontal: 20, paddingTop: 12 },
  identityCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 16,
    borderRadius: 20,
    borderWidth: 1,
    padding: 18,
    marginBottom: 24,
  },
  avatar: {
    width: 56,
    height: 56,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { fontSize: 20, letterSpacing: -0.5 },
  identityBody: { flex: 1, minWidth: 0 },
  identityTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap',
    marginBottom: 8,
  },
  identityName: { fontSize: 20, letterSpacing: -0.3, flexShrink: 1 },
  guestPill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  guestPillText: { fontSize: 12 },
  metaRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 6 },
  metaText: { fontSize: 14, flex: 1 },
  guestNote: { fontSize: 14, lineHeight: 21, marginTop: 4 },
  sectionLabel: {
    fontSize: 12,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    marginBottom: 10,
    marginTop: 4,
  },
  sectionHint: { fontSize: 14, lineHeight: 20, marginBottom: 12, marginTop: -4 },
  settingsCard: {
    borderRadius: 18,
    borderWidth: 1,
    overflow: 'hidden',
    marginBottom: 16,
  },
  settingsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  rowIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowIconSm: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsRowText: { flex: 1, minWidth: 0, paddingRight: 8 },
  rowTitle: { fontSize: 16, letterSpacing: -0.2 },
  rowSub: { fontSize: 13, lineHeight: 18, marginTop: 4, maxWidth: 260 },
  rowHairline: { height: StyleSheet.hairlineWidth, marginLeft: 62 },
  metricToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  metricLabel: { flex: 1, fontSize: 15, lineHeight: 20 },
  primaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingVertical: 16,
    borderRadius: 16,
    marginBottom: 8,
  },
  primaryBtnText: { color: '#fff', fontSize: 16 },
  dangerBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingVertical: 16,
    borderRadius: 16,
    borderWidth: 1.5,
    marginBottom: 10,
  },
  dangerBtnText: { color: '#dc2626', fontSize: 16 },
  secondaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingVertical: 16,
    borderRadius: 16,
    borderWidth: 1,
  },
  secondaryBtnText: { fontSize: 16 },
  footer: { fontSize: 12, lineHeight: 18, marginTop: 28, textAlign: 'center', paddingHorizontal: 12 },
});
